### PR TITLE
Adopt Reflection 0.15.0 to support Swift 4. All tests pass. 

### PR DESCRIPTION
**Pull request by jseibert**

### CODE REVIEW

**Comment by paulofaria** [comment]
looks like tests failed on macOS?

**Comment by jseibert** [comment]
BinaryInteger, the reason for the failed test, is available in Xcode 9, so maybe Travis is misconfigured? [https://travis-ci.org/GraphQLSwift/GraphQL/jobs/281807996](url)

Everything works for me:

> Jeffs-MacBook-Pro GraphQL-jseibert (master) $ swift --version
Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
Target: x86_64-apple-macosx10.9
Jeffs-MacBook-Pro GraphQL-jseibert (master) $ swift build
Compile Swift Module 'GraphQL' (65 sources)
Jeffs-MacBook-Pro GraphQL-jseibert (master) $ swift test
Compile Swift Module 'GraphQLTests' (17 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/GraphQLPackageTests.xctest/Contents/MacOS/GraphQLPackageTests
Test Suite 'All tests' started at 2017-10-01 06:23:08.750
Test Suite 'GraphQLPackageTests.xctest' started at 2017-10-01 06:23:08.750
Test Suite 'FieldExecutionStrategyTests' started at 2017-10-01 06:23:08.750
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithMultipleFieldErrors]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithMultipleFieldErrors]' passed (0.347 seconds).
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithMultipleFields]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithMultipleFields]' passed (0.111 seconds).
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithSingleField]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithSingleField]' passed (0.110 seconds).
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithSingleFieldError]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testConcurrentDispatchFieldExecutionStrategyWithSingleFieldError]' passed (0.112 seconds).
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithMultipleFieldErrors]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithMultipleFieldErrors]' passed (1.063 seconds).
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithMultipleFields]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithMultipleFields]' passed (1.066 seconds).
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithSingleField]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithSingleField]' passed (0.111 seconds).
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithSingleFieldError]' started.
Test Case '-[GraphQLTests.FieldExecutionStrategyTests testSerialFieldExecutionStrategyWithSingleFieldError]' passed (0.107 seconds).
Test Suite 'FieldExecutionStrategyTests' passed at 2017-10-01 06:23:11.779.
	 Executed 8 tests, with 0 failures (0 unexpected) in 3.028 (3.029) seconds
Test Suite 'FieldsOnCorrectTypeTests' started at 2017-10-01 06:23:11.779
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenAliasedFieldTargetNotDefined]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenAliasedFieldTargetNotDefined]' passed (0.010 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenAliasedLyingFieldTargetNotDefined]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenAliasedLyingFieldTargetNotDefined]' passed (0.004 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenDeepFieldNotDefined]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenDeepFieldNotDefined]' passed (0.006 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenDefinedOnImplementorsButNotInterface]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenDefinedOnImplementorsButNotInterface]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenFieldNotDefined]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenFieldNotDefined]' passed (0.004 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenFieldNotDefinedOnInlineFragment]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenFieldNotDefinedOnInlineFragment]' passed (0.004 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenNotDefinedOnInterface]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenNotDefinedOnInterface]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenSubFieldNotDefined]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenSubFieldNotDefined]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenTypeKnownAgain]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testInvalidWhenTypeKnownAgain]' passed (0.002 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWhenMetaFieldSelectionOnUnion]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWhenMetaFieldSelectionOnUnion]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithAliasedInterfaceFieldSelection]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithAliasedInterfaceFieldSelection]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithAliasedObjectFieldSelection]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithAliasedObjectFieldSelection]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithIgnoresFieldsOnUnknownType]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithIgnoresFieldsOnUnknownType]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithInlineFragment]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithInlineFragment]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithInterfaceFieldSelection]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithInterfaceFieldSelection]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithLyingAliasSelection]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithLyingAliasSelection]' passed (0.001 seconds).
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithObjectFieldSelection]' started.
Test Case '-[GraphQLTests.FieldsOnCorrectTypeTests testValidWithObjectFieldSelection]' passed (0.001 seconds).
Test Suite 'FieldsOnCorrectTypeTests' passed at 2017-10-01 06:23:11.820.
	 Executed 17 tests, with 0 failures (0 unexpected) in 0.040 (0.041) seconds
Test Suite 'HelloWorldTests' started at 2017-10-01 06:23:11.820
Test Case '-[GraphQLTests.HelloWorldTests testBoyhowdy]' started.
Test Case '-[GraphQLTests.HelloWorldTests testBoyhowdy]' passed (0.001 seconds).
Test Case '-[GraphQLTests.HelloWorldTests testHello]' started.
Test Case '-[GraphQLTests.HelloWorldTests testHello]' passed (0.001 seconds).
Test Suite 'HelloWorldTests' passed at 2017-10-01 06:23:11.822.
	 Executed 2 tests, with 0 failures (0 unexpected) in 0.002 (0.002) seconds
Test Suite 'InstrumentationTests' started at 2017-10-01 06:23:11.822
Test Case '-[GraphQLTests.InstrumentationTests testDispatchQueueInstrumentationWrapper]' started.
Test Case '-[GraphQLTests.InstrumentationTests testDispatchQueueInstrumentationWrapper]' passed (0.003 seconds).
Test Case '-[GraphQLTests.InstrumentationTests testInstrumentationCalls]' started.
Test Case '-[GraphQLTests.InstrumentationTests testInstrumentationCalls]' passed (0.002 seconds).
Test Suite 'InstrumentationTests' passed at 2017-10-01 06:23:11.826.
	 Executed 2 tests, with 0 failures (0 unexpected) in 0.004 (0.004) seconds
Test Suite 'LexerTests' started at 2017-10-01 06:23:11.826
Test Case '-[GraphQLTests.LexerTests testBOMHeader]' started.
Test Case '-[GraphQLTests.LexerTests testBOMHeader]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testDashInName]' started.
Test Case '-[GraphQLTests.LexerTests testDashInName]' passed (0.001 seconds).
Test Case '-[GraphQLTests.LexerTests testDoubleLinkedList]' started.
Test Case '-[GraphQLTests.LexerTests testDoubleLinkedList]' passed (0.001 seconds).
Test Case '-[GraphQLTests.LexerTests testErrorsRespectWhitespaces]' started.
Test Case '-[GraphQLTests.LexerTests testErrorsRespectWhitespaces]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testInvalidCharacter]' started.
Test Case '-[GraphQLTests.LexerTests testInvalidCharacter]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testNumberErrors]' started.
Test Case '-[GraphQLTests.LexerTests testNumberErrors]' passed (0.003 seconds).
Test Case '-[GraphQLTests.LexerTests testNumbers]' started.
Test Case '-[GraphQLTests.LexerTests testNumbers]' passed (0.001 seconds).
Test Case '-[GraphQLTests.LexerTests testRecordsLineAndColumn]' started.
Test Case '-[GraphQLTests.LexerTests testRecordsLineAndColumn]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testSkipsCommas]' started.
Test Case '-[GraphQLTests.LexerTests testSkipsCommas]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testSkipsComments]' started.
Test Case '-[GraphQLTests.LexerTests testSkipsComments]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testSkipsWhitespace]' started.
Test Case '-[GraphQLTests.LexerTests testSkipsWhitespace]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testStringErrors]' started.
Test Case '-[GraphQLTests.LexerTests testStringErrors]' passed (0.001 seconds).
Test Case '-[GraphQLTests.LexerTests testStrings]' started.
Test Case '-[GraphQLTests.LexerTests testStrings]' passed (0.001 seconds).
Test Case '-[GraphQLTests.LexerTests testSymbols]' started.
Test Case '-[GraphQLTests.LexerTests testSymbols]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testTokenDescription]' started.
Test Case '-[GraphQLTests.LexerTests testTokenDescription]' passed (0.000 seconds).
Test Case '-[GraphQLTests.LexerTests testUnknownCharacterErrors]' started.
Test Case '-[GraphQLTests.LexerTests testUnknownCharacterErrors]' passed (0.001 seconds).
Test Suite 'LexerTests' passed at 2017-10-01 06:23:11.838.
	 Executed 16 tests, with 0 failures (0 unexpected) in 0.010 (0.011) seconds
Test Suite 'MapTests' started at 2017-10-01 06:23:11.838
Test Case '-[GraphQLTests.MapTests testConversion]' started.
Test Case '-[GraphQLTests.MapTests testConversion]' passed (0.001 seconds).
Test Case '-[GraphQLTests.MapTests testCreation]' started.
Test Case '-[GraphQLTests.MapTests testCreation]' passed (0.001 seconds).
Test Case '-[GraphQLTests.MapTests testDebugDescription]' started.
Test Case '-[GraphQLTests.MapTests testDebugDescription]' passed (0.001 seconds).
Test Case '-[GraphQLTests.MapTests testDescription]' started.
Test Case '-[GraphQLTests.MapTests testDescription]' passed (0.000 seconds).
Test Case '-[GraphQLTests.MapTests testEquality]' started.
Test Case '-[GraphQLTests.MapTests testEquality]' passed (0.000 seconds).
Test Case '-[GraphQLTests.MapTests testIndexPath]' started.
Test Case '-[GraphQLTests.MapTests testIndexPath]' passed (0.001 seconds).
Test Case '-[GraphQLTests.MapTests testMapInitializable]' started.
Test Case '-[GraphQLTests.MapTests testMapInitializable]' passed (0.000 seconds).
Test Case '-[GraphQLTests.MapTests testMapRepresentable]' started.
Test Case '-[GraphQLTests.MapTests testMapRepresentable]' passed (0.000 seconds).
Test Suite 'MapTests' passed at 2017-10-01 06:23:11.842.
	 Executed 8 tests, with 0 failures (0 unexpected) in 0.004 (0.005) seconds
Test Suite 'ParserTests' started at 2017-10-01 06:23:11.842
Test Case '-[GraphQLTests.ParserTests testAnonymousMutationOperation]' started.
Test Case '-[GraphQLTests.ParserTests testAnonymousMutationOperation]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testAnonymousSubscriptionOperation]' started.
Test Case '-[GraphQLTests.ParserTests testAnonymousSubscriptionOperation]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testCreateAST]' started.
Test Case '-[GraphQLTests.ParserTests testCreateAST]' passed (0.001 seconds).
Test Case '-[GraphQLTests.ParserTests testErrorMessages]' started.
Test Case '-[GraphQLTests.ParserTests testErrorMessages]' passed (0.002 seconds).
Test Case '-[GraphQLTests.ParserTests testKitchenSink]' started.
Test Case '-[GraphQLTests.ParserTests testKitchenSink]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testLocationSource]' started.
Test Case '-[GraphQLTests.ParserTests testLocationSource]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testLocationTokens]' started.
Test Case '-[GraphQLTests.ParserTests testLocationTokens]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testNamedMutationOperation]' started.
Test Case '-[GraphQLTests.ParserTests testNamedMutationOperation]' passed (0.001 seconds).
Test Case '-[GraphQLTests.ParserTests testNamedSubscriptionOperation]' started.
Test Case '-[GraphQLTests.ParserTests testNamedSubscriptionOperation]' passed (0.001 seconds).
Test Case '-[GraphQLTests.ParserTests testNoLocation]' started.
Test Case '-[GraphQLTests.ParserTests testNoLocation]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testNonKeywordAsName]' started.
Test Case '-[GraphQLTests.ParserTests testNonKeywordAsName]' passed (0.012 seconds).
Test Case '-[GraphQLTests.ParserTests testParseType]' started.
Test Case '-[GraphQLTests.ParserTests testParseType]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testParseValue]' started.
Test Case '-[GraphQLTests.ParserTests testParseValue]' passed (0.000 seconds).
Test Case '-[GraphQLTests.ParserTests testVariableInlineValues]' started.
Test Case '-[GraphQLTests.ParserTests testVariableInlineValues]' passed (0.001 seconds).
Test Suite 'ParserTests' passed at 2017-10-01 06:23:11.863.
	 Executed 14 tests, with 0 failures (0 unexpected) in 0.019 (0.020) seconds
Test Suite 'PersistedQueriesTests' started at 2017-10-01 06:23:11.863
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithUnknownId]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithUnknownId]' passed (0.000 seconds).
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithWithParseError]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithWithParseError]' passed (0.000 seconds).
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithWithResult]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithWithResult]' passed (0.000 seconds).
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithWithValidationErrors]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testGraphQLWithWithValidationErrors]' passed (0.001 seconds).
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithParseError]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithParseError]' passed (0.000 seconds).
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithResult]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithResult]' passed (0.000 seconds).
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithUnknownId]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithUnknownId]' passed (0.000 seconds).
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithValidationErrors]' started.
Test Case '-[GraphQLTests.PersistedQueriesTests testLookupWithValidationErrors]' passed (0.001 seconds).
Test Suite 'PersistedQueriesTests' passed at 2017-10-01 06:23:11.867.
	 Executed 8 tests, with 0 failures (0 unexpected) in 0.003 (0.004) seconds
Test Suite 'SchemaParserTests' started at 2017-10-01 06:23:11.867
Test Case '-[GraphQLTests.SchemaParserTests testDoubleValueEnum]' started.
Test Case '-[GraphQLTests.SchemaParserTests testDoubleValueEnum]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testScalar]' started.
Test Case '-[GraphQLTests.SchemaParserTests testScalar]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleExtension]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleExtension]' passed (0.001 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithArg]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithArg]' passed (0.001 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithArgDefaultValue]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithArgDefaultValue]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithListArg]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithListArg]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithTwoArgs]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleFieldWithTwoArgs]' passed (0.001 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleInputObject]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleInputObject]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleInputObjectWithArgs]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleInputObjectWithArgs]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleInterface]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleInterface]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleNonNullType]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleNonNullType]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleType]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleType]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleTypeInheritingInterface]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleTypeInheritingInterface]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleTypeInheritingMultipleInterfaces]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleTypeInheritingMultipleInterfaces]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSimpleUnion]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSimpleUnion]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testSingleValueEnum]' started.
Test Case '-[GraphQLTests.SchemaParserTests testSingleValueEnum]' passed (0.000 seconds).
Test Case '-[GraphQLTests.SchemaParserTests testUnionTwoTypes]' started.
Test Case '-[GraphQLTests.SchemaParserTests testUnionTwoTypes]' passed (0.000 seconds).
Test Suite 'SchemaParserTests' passed at 2017-10-01 06:23:11.874.
	 Executed 17 tests, with 0 failures (0 unexpected) in 0.006 (0.007) seconds
Test Suite 'StarWarsIntrospectionTests' started at 2017-10-01 06:23:11.874
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionCharacterKindQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionCharacterKindQuery]' passed (0.003 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidDescriptionQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidDescriptionQuery]' passed (0.003 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidFieldsQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidFieldsQuery]' passed (0.009 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidKindQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidKindQuery]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidNestedFieldsQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidNestedFieldsQuery]' passed (0.008 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidTypeQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionDroidTypeQuery]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionFieldArgsQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionFieldArgsQuery]' passed (0.014 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionQueryTypeQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionQueryTypeQuery]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionTypeQuery]' started.
Test Case '-[GraphQLTests.StarWarsIntrospectionTests testIntrospectionTypeQuery]' passed (0.002 seconds).
Test Suite 'StarWarsIntrospectionTests' passed at 2017-10-01 06:23:11.918.
	 Executed 9 tests, with 0 failures (0 unexpected) in 0.044 (0.045) seconds
Test Suite 'StarWarsQueryTests' started at 2017-10-01 06:23:11.918
Test Case '-[GraphQLTests.StarWarsQueryTests testCheckTypeOfLukeQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testCheckTypeOfLukeQuery]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testCheckTypeOfR2Query]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testCheckTypeOfR2Query]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testDuplicateFieldsQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testDuplicateFieldsQuery]' passed (0.004 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchLukeAliasedQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchLukeAliasedQuery]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchLukeAndLeiaAliasedQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchLukeAndLeiaAliasedQuery]' passed (0.003 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchLukeQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchLukeQuery]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchSomeIDQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testFetchSomeIDQuery]' passed (0.007 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testHeroNameAndFriendsQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testHeroNameAndFriendsQuery]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testHeroNameQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testHeroNameQuery]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testNestedQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testNestedQuery]' passed (0.004 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testNonNullableFieldsQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testNonNullableFieldsQuery]' passed (0.004 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testOptionalVariable]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testOptionalVariable]' passed (0.003 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testSecretBackstoryAliasQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testSecretBackstoryAliasQuery]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testSecretBackstoryListQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testSecretBackstoryListQuery]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testSecretBackstoryQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testSecretBackstoryQuery]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsQueryTests testUseFragmentQuery]' started.
Test Case '-[GraphQLTests.StarWarsQueryTests testUseFragmentQuery]' passed (0.004 seconds).
Test Suite 'StarWarsQueryTests' passed at 2017-10-01 06:23:11.962.
	 Executed 16 tests, with 0 failures (0 unexpected) in 0.043 (0.043) seconds
Test Suite 'StarWarsValidationTests' started at 2017-10-01 06:23:11.962
Test Case '-[GraphQLTests.StarWarsValidationTests testDroidFieldInFragment]' started.
Test Case '-[GraphQLTests.StarWarsValidationTests testDroidFieldInFragment]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsValidationTests testDroidFieldInInlineFragment]' started.
Test Case '-[GraphQLTests.StarWarsValidationTests testDroidFieldInInlineFragment]' passed (0.002 seconds).
Test Case '-[GraphQLTests.StarWarsValidationTests testDroidFieldOnCharacter]' started.
Test Case '-[GraphQLTests.StarWarsValidationTests testDroidFieldOnCharacter]' passed (0.004 seconds).
Test Case '-[GraphQLTests.StarWarsValidationTests testHeroFieldsOnScalarQuery]' started.
Test Case '-[GraphQLTests.StarWarsValidationTests testHeroFieldsOnScalarQuery]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsValidationTests testHeroNoFieldsQuery]' started.
Test Case '-[GraphQLTests.StarWarsValidationTests testHeroNoFieldsQuery]' passed (0.001 seconds).
Test Case '-[GraphQLTests.StarWarsValidationTests testHeroSpaceshipQuery]' started.
Test Case '-[GraphQLTests.StarWarsValidationTests testHeroSpaceshipQuery]' passed (0.005 seconds).
Test Case '-[GraphQLTests.StarWarsValidationTests testNestedQueryWithFragment]' started.
Test Case '-[GraphQLTests.StarWarsValidationTests testNestedQueryWithFragment]' passed (0.007 seconds).
Test Suite 'StarWarsValidationTests' passed at 2017-10-01 06:23:11.983.
	 Executed 7 tests, with 0 failures (0 unexpected) in 0.021 (0.021) seconds
Test Suite 'VisitorTests' started at 2017-10-01 06:23:11.983
Test Case '-[GraphQLTests.VisitorTests test]' started.
Test Case '-[GraphQLTests.VisitorTests test]' passed (0.000 seconds).
Test Suite 'VisitorTests' passed at 2017-10-01 06:23:11.983.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'GraphQLPackageTests.xctest' passed at 2017-10-01 06:23:11.983.
	 Executed 125 tests, with 0 failures (0 unexpected) in 3.225 (3.233) seconds
Test Suite 'All tests' passed at 2017-10-01 06:23:11.984.
	 Executed 125 tests, with 0 failures (0 unexpected) in 3.225 (3.234) seconds
Jeffs-MacBook-Pro GraphQL-jseibert (master) $

**Comment by paulofaria** [comment]
Oh you have to change Xcode's version [here](https://github.com/GraphQLSwift/GraphQL/blob/master/.travis.yml#L8) to `xcode9` as in [here](https://docs.travis-ci.com/user/reference/osx/#OS-X-Version). Can you please do that? 😊

**Comment by paulofaria** [comment]
I was able to update your PR mysellf. let's wait for travis now.

**Comment by paulofaria** [comment]
Passed. Thanks a lot!

**Comment by jseibert** [comment]
Woot! Thanks @paulofaria!! Sorry, I was offline for a bit.

**Pull request merged**
