### PR TITLE
Incremented Runtime Version For Swift 5.0 Compatibility

### PR DESCRIPTION
**Pull request by tjarksaul**

### CODE REVIEW

**Comment by noahemmet** [comment]
In `Package.swift`, should `// swift-tools-version:4.0` be updated to `// swift-tools-version:5.0`?

**Comment by noahemmet** [comment]
I also noticed a number of tests weren't passing (locally, at least), but I wasn't able to check if they had passed pre-Swift 5.

**Comment by nichdu** [comment]
> In `Package.swift`, should `// swift-tools-version:4.0` be updated to `// swift-tools-version:5.0`?

It is possible but not neccessary. 4.0 allows it to be built with Swift 4, too.

**Comment by noahemmet** [comment]
Ah. I wasn't sure if the new [Runtime changes](https://github.com/wickwirew/Runtime/pull/38) were backwards compatible with Swift 4.

**Pull request closed without merging**
