### PR TITLE
Fixes bug with multithreaded event loop

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**

### CODE REVIEW

**Comment by NeedleInAJayStack** [comment]
Hey @paulofaria, just let me know if you'd like me to assign you as the reviewer, or what your workflow is. Thanks!

**Comment by paulofaria** [comment]
It looks like GH Actions settings have changed and CI isn't passing anymore. I'll take a look st that later this week if you don't beat me to it.

**Comment by NeedleInAJayStack** [comment]
@paulofaria Good call. I just fixed the GitHub CI issue in this pull request, and it's passing now. I also put in an additional pull request to fix the same issue in Graphiti: https://github.com/GraphQLSwift/Graphiti/pull/53

**Comment by paulofaria** [comment]
@NeedleInAJayStack thank you very much!

**Pull request merged**
