### PR TITLE
Modify blockstring support to be closer to canonical js implementation

### PR DESCRIPTION
**Pull request by haikusw**
Modified the blockstring support implementation to be closer to canonical js implementation, and also add \””” support as well as a few more tests.

### CODE REVIEW

**Comment by haikusw** [comment]
Did not rewrite `blockStringValue` to be multiple routines since I implemented it as directly to the specification as possible and it seems to pass all the tests in ways that seem correct.

I'd like to compare the output of the js version for block strings but I don't have a js setup and the js sandbox wouldn't let me access Lexer directly (not sure why).

**Comment by haikusw** [comment]
I also have an updated version of the description support PR that is similarly closer to the canonical js implementation but it requires this update to be merged first.

**Comment by haikusw** [comment]
> @haikusw Looks good to me, is it ready to merge?

Thank you.  Yes, ready to merge.

**Comment by paulofaria** [comment]
Thank you! @haikusw

**Pull request merged**
