### PR TITLE
Handling clashes when a version of the type is only a reference

### PR DESCRIPTION
**Pull request by nerdsupremacist**

### CODE REVIEW

**Comment by paulofaria** [comment]
Can you please check why the test are failing and fix the issues so I can merge?

**Comment by nerdsupremacist** [comment]
Oh that's weird. It failed checking out Swift-Nio. Perhaps retriggering it would help

**Comment by nerdsupremacist** [comment]
well it fixed it in linux. Let's see if it also passes for Mac

**Comment by paulofaria** [comment]
Hello, @nerdsupremacist. I'm closing this PR because it is doing much more then what is in the title. I believe this happened because you based your PR from your master branch. This caused all of the other changes to appear here as well. I start trying to resolve conflicts, but since you based this PR off of master, I would be committing to your master branch and that wouldn't be cool. Feel free to create another PR based on a separate branch. Thank you!

**Pull request closed without merging**
