### PR TITLE
Visitor Fixes and Editing Support

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**
This adds editing support to the AST Visitor system. In addition, it also:

- Adds all graphql-js visitor tests cases, both for editing and for normal visitor operation
- Fixes a bug where the Visitor would not visit all Directive, ListType, or ListValue properties
- Fixes a bug where Visitor path would be generated incorrectly
- Improves Visitor null safety

### CODE REVIEW

**Comment by NeedleInAJayStack** [comment]
@paulofaria Looks like the `any` keyword isn't supported in Swift 5.5. What do you think about dropping support for that version?

**Comment by paulofaria** [comment]
Hm, I'm not sure we can, based on the SSWG guidelines? Can't we just remove the keyword so it's backwards compatible?

**Comment by NeedleInAJayStack** [comment]
Oh weird - I added `any` because I thought I saw error messages, but I wasn't able to recreate them. I've removed the `any` keywords.

Maybe not relevant anymore, but I don't think SSWG requires extensive backsupport - New NIO versions only back-support to Swift 5.7: https://github.com/apple/swift-nio/#swiftnio-2

**Review by paulofaria — DISMISSED** [review]
Beautiful!

**Comment by NeedleInAJayStack** [comment]
Thanks @paulofaria. I just made one last small change to back-support the public Node Protocol API, making this a minor change instead of major.

Mind approving again?

**Review by paulofaria — APPROVED** [review]

**Pull request merged**
