### PR TITLE
Adds support for reference types on Input fields

### PR DESCRIPTION
**Pull request by NeedleInAJayStack**
This adds support for recursive inputs (inputs that reference themselves). For example, the following is now a valid input definition:

```
input BoolExp {
  and: [BoolExp]
  or: [BoolExp]
  val: Bool
}
```

This builds on the Type and Interface recursion support (via `TypeReference`), by extending that functionality to Inputs as well.

It also renames a few Input Field types to be more consistent with the equivalent Type Field types

### CODE REVIEW

**Review by paulofaria — APPROVED** [review]
LGTM! Feel free to merge and tag it! 🙂

**Comment by NeedleInAJayStack** [comment]
@paulofaria Hey, just a reminder that I'm happy to merge and tag, but I don't have write access. Any chance you could provide me with it?

**Comment by paulofaria** [comment]
Hey! I'll do that Today. Sorry.

**Comment by paulofaria** [comment]
@alexsteinerde Did you receive the invitation?

**Comment by paulofaria** [comment]
@alexsteinerde Sorry, the message was meant for @NeedleInAJayStack.

**Comment by paulofaria** [comment]
@NeedleInAJayStack I created a Maintainers team. You should now have access to all repos. 😄

**Comment by NeedleInAJayStack** [comment]
Awesome, I do have access now! Thanks @paulofaria

**Comment by NeedleInAJayStack** [comment]
@paulofaria I added 'macos-latest' to the CI build file so that we won't run into PR "status check" issues in the future. However, the commit reset the approval. Do you mind re-approving this?

**Review by paulofaria — APPROVED** [review]

**Comment by paulofaria** [comment]
Done!

**Pull request merged**
