### PR TITLE
Introduce futures and SwiftNIO

### PR DESCRIPTION
**Pull request by kimdv**
Hi @paulofaria  

I started to solve my own issue #39 

I'm currently facing an issue with `func completeValue`

`return result.thenThrowing { result -> EventLoopFuture<Any?> in ... }` is returning a Future, and I can't get that resolved. 

Maybe you can help me out? :)

// Kim

### CODE REVIEW

**Comment by kimdv** [comment]
Thanks @paulofaria for the quick answer !
I have been looking into #37 and also compared a lot to the GraphQL-js. 

The problem is that a futures result is a future. And I think if I can get that resolved, somehow all the tests passes. 

Maybe @jseibert can help me out so we can finish it?

**Comment by jseibert** [comment]
@kimdv can you give more details as to what problem you're facing? Generally, yes, you want the result to be a future, so I'm confused.  

If you're willing to take a vapor/core dependency, 
https://github.com/digits-labs/graphiti
https://github.com/digits-labs/graphql
are now rock-solid for me. (Ignore the readme's, I haven't updated them)

You need to route the futures all the way through, i.e. `graphql(...)` returns an `EventLoopFuture<Map>`

In Graphiti, the schema-builders support both future fields, and normal fields:

```
try builder.field(name: "organization", futureType: Organization.self) { (selfInstance, _: NoArguments, req: Request, _) in
    // Returns an EventLoopFuture<Organization>
    return try selfInstance.organization.get(on: req)
}

try builder.field(name: "name", type: String.self) { (selfInstance, _: NoArguments, req: Request, _) in
    // Returns a String directly, no future needed. 
    return selfInstance.name
}
```
In Vapor, the Request object is an EventLoopGroup, which I have forcibly routed through as the Context param.

**Comment by kimdv** [comment]
Maybe I'm misunderstanding something. 

I try to update the tests, and the test crashes: 
As you can see on the attached screenshot, the value for `__schema` is a `<EventLoopFuture<Any?>`

Either I need to update the test or I'm doing something wong.. :)

screen shot 2018-05-28 at 19 41 38

**Comment by jseibert** [comment]
Looks like your implementation isn't entirely correct. Data should be a `Future<[String: Any]>`, not a `[String: Future<Any>]`. You need to flatten the dictionary futures.

**Comment by kimdv** [comment]
@jseibert I found a solution. 
Using Vapors/Core [flatMap](https://github.com/GraphQLSwift/GraphQL/pull/41/commits/9f4456e2b8f04e9cbfd0fe0250fc4bcd6ffad729#diff-47c402846910a15e19f25220b0c136b7R882) solved all my problems

**Comment by paulofaria** [comment]
This is great! I'm a bit off the grid now so I can't properly review everything. I'll review everything by sunday though. Thanks a lot!

**Pull request merged**
