### PR TITLE
Update to swift3.1

### PR DESCRIPTION
**Pull request by sportlabsMike**
In swift 3.1 on linux RegularExpression became NSRegularExpression once again bringing it back in line with macOS.
This change updates the travis build to use swift 3.1 and removes the linux specific switches which were using 'RegularExpression' instead of 'NSRegularExpression'.

### CODE REVIEW

**Comment by paulofaria** [comment]
Hey! Thanks a lot! By the way, Is the env var necessary? 

https://github.com/GraphQLSwift/GraphQL/pull/19/files#diff-354f30a63fb0907d4ad57269548329e3R6

We already have `.swift-version` file:

https://github.com/GraphQLSwift/GraphQL/blob/master/.swift-version

I think it's best to update the file and remove the env var.

**Comment by sportlabsMike** [comment]
Hi. Thanks, I didn't spot the .swift-version file first time round!
I've updated that and removed the env var from .travis.yml

**Comment by sportlabsMike** [comment]
Now that I realise the .swift-version file takes precedence I can revert the .travis.yml back to using https://raw.githubusercontent.com/lgaches/swifttravisci/master/travisci if you prefer?
The reason I replaced it with individual script commands in the .travis.yml was because it had SWIFT_VERSION = 3.0 within it ...

**Comment by paulofaria** [comment]
yeah that would be nice!

**Comment by sportlabsMike** [comment]
It looks like https://raw.githubusercontent.com/lgaches/swifttravisci/master/travisci is overriding the .swift-version file so by using it 3.0.1 is still being installed for the linux build :(
I'll go back to what I had. It's probably better not to rely on an external script for this anyway?

**Comment by paulofaria** [comment]
thanks man!

**Pull request merged**
