### PR TITLE
Add working Linux tests

### PR DESCRIPTION
**Pull request by adam-fowler**
As with Graphiti, GraphQL does not have working Linux tests.
This PR resolves this.

### CODE REVIEW

**Comment by adam-fowler** [comment]
The thread sanitizer is complaining.

**Comment by adam-fowler** [comment]
Removed the thread sanitizer. Issues are with Runtime package and cannot be resolved here. I've added an issue https://github.com/wickwirew/Runtime/issues/87

**Comment by adam-fowler** [comment]
Is there any reason GraphQL doesn't use `Mirror` instead of the Runtime package?

**Comment by paulofaria** [comment]
Back then, Mirror wasn't powerful enough! Do you reckon it is possible to replace Runtime with Mirror? I haven't heard of any updates regarding reflection in Swift. I'd love to simplify the codebase and remove the dependency, if possible.

**Comment by adam-fowler** [comment]
> Back then, Mirror wasn't powerful enough! Do you reckon it is possible to replace Runtime with Mirror? I haven't heard of any updates regarding reflection in Swift. I'd love to simplify the codebase and remove the dependency, if possible.

All you seem to be using it for is extracting values out of a type using the variable name. I'll add a PR to demonstrate

**Comment by paulofaria** [comment]
@adam-fowler I think updating from master should solve the issue with GH actions.

**Comment by paulofaria** [comment]
Basically adding the macos-latest?

**Comment by adam-fowler** [comment]
@paulofaria This change will need a change to the required tests.  

The ubuntu tests you had before didn't test anything. This is why I added this PR. But the change uses the swift docker images which have different names to the ubuntu images required at the moment. The swift docker images are better to use because we can be specific about which version of swift we want running.

As an aside isn't macos-10.15 the same as macos-latest?

**Comment by paulofaria** [comment]
As an aside isn't macos-10.15 the same as macos-latest?

@adam-fowler Yeah, I think so. @alexsteinerde might chime in and let us know why adding "macos-latest" fixes the GH actions stall issue. If changing to "macos-latest" and removing macos-10.15 works, I'm cool with just using "macos-latest".

**Comment by NeedleInAJayStack** [comment]
@adam-fowler With this change, should we remove the ubuntu items from [this line in the existing workflow yml](https://github.com/GraphQLSwift/GraphQL/blob/ebd2ea40676f8bcbdfd6088c408f3ed321c1a905/.github/workflows/build.yml#L16)?

**Comment by adam-fowler** [comment]
Looks like it needs updated to support 5.5 and 5.6. Although since I posted the new swift install actions are available which could simplify this more. I'll rebuild this using them.

**Comment by adam-fowler** [comment]
Can we get rid of the required tests `Build and test on macos-10.15` and `Build and test on ubuntu-18.04`. @NeedleInAJayStack don't know if you have the power. Maybe @paulofaria can do this.

**Comment by paulofaria** [comment]
Added @NeedleInAJayStack to the admins team. He should have full access now.

**Comment by paulofaria** [comment]
Closed by accident.

**Comment by paulofaria** [comment]
Hm, not sure how I can get rid of that? Maybe we should force merge, then that requirement will be gone, since it won't be in the yml file anymore? This looks like a GH bug, I reckon.

**Comment by adam-fowler** [comment]
> Hm, not sure how I can get rid of that? Maybe we should force merge, then that requirement will be gone, since it won't be in the yml file anymore? This looks like a GH bug, I reckon.

It is in the settings for the project (something only admins can access). Do you have branch protection setup?

**Comment by NeedleInAJayStack** [comment]
I've removed `Build and test on macos-10.15` and `Build and test on ubuntu-18.04` from the `master` branch protection rules

**Comment by NeedleInAJayStack** [comment]
Scratch that - I've changed the branch protection rules to be the actions that ran when this was merged to master. Specifically, the actions required are:

- `Build and test on macos-latest`
- `Build 5.4 on ubuntu-latest`
- `Build 5.5 on ubuntu-latest`
- `Build 5.6 on ubuntu-latest`

**Comment by adam-fowler** [comment]
I think it's pretty pointless adding required builds. You already require an admin approval. Also the required builds will change overtime as new versions of swift are released. 

Swift NIO is only ever planning to support the last three versions of swift so there is no real point for a project reliant of NIO trying to support more version of swift than that. So when 5.7 is released support for 5.4 won't be required. Of course you can still support 5.4 if you want.

**Comment by NeedleInAJayStack** [comment]
I agree with you Adam - requiring code owner approval seems sufficient to me. I'll let @paulofaria make the final call on this one though since he's been the primary maintainer.

**Comment by paulofaria** [comment]
Yeah! Let's do it!

**Comment by NeedleInAJayStack** [comment]
Awesome, I've removed the required status checks from GraphQL and aligned the projects throughout GraphQLSwift to have the same main branch protection settings. Thanks guys!

**Comment by paulofaria** [comment]
Thank you, Jay!

**Pull request merged**
